### ISSUE TITLE
CarCharging module not working

### ISSUE THREAD

**Issue by mwkrieger** [MikeBishop/MMM-Powerwall#15]
This morning, the fantastic CarCharging module stopped working. I think this is because I enabled 2 factor auth on my Tesla account. 

I created new access tokens using Tesla-Screen as indicated, changed the tokens.json file, and restarted MM. I'm still not seeing the charging information. 

Does anyone know of a workaround?

**Comment by MikeBishop** [comment]
Interesting.  I haven't tested with 2FA.  I have seen brief periods where the API appears to return an empty list of vehicles; I haven't been able to pin down why, but it seems to fix itself after a few hours.  I'll try enabling 2FA and see what I get.

Are the other graphs working, or are you only using CarCharging?

**Comment by mwkrieger** [comment]
All the other graphs are working fine. No problems.

**Comment by MikeBishop** [comment]
Okay, that's sounding more like the empty vehicle list, then.  If the other graphs are working with cloud data (i.e. anything that's not instantaneous data from the Powerwall), that means API access is working.  I'd restart after a couple hours and see if it's back to normal.

I might have to implement something like what the Tesla app appears to do, storing the vehicles on the account to a local file and then validating that they're still accessible, rather than always trusting the list of vehicles in the cloud.  I've tried to avoid storing anything locally except the tokens, but....

**Comment by mwkrieger** [comment]
Ok, great. It hasn't been working since this AM after a few reboots. I'll let it run the rest of the day and see if it comes back. Attached is a screenshot if it helps you - shows a 'full battery', but no other info.
![20201008_134832](https://user-images.githubusercontent.com/3599238/95495436-6d9ca600-096d-11eb-9103-6d3a20a614c0.jpg)

**Comment by MikeBishop** [comment]
Yeah, that's what mine looks like when it gets into that state, too.  It's clearly able to get the cloud info (without the cloud access, "today" info doesn't populate until after the next midnight; "yesterday" info populates the following midnight; Self-Powered, EnergyBar, and PowerLine don't populate at all).

Next time I have a repro, I'll have to test whether I'm able to hit the vehicle by ID if I know it's there, even if it's not showing in the list....  If so, a local cache of vehicles would be the simplest solution.

**Comment by MikeBishop** [comment]
Just checking in - did this eventually clear?

**Comment by mwkrieger** [comment]
No, it's still blank.

I did have a home link installed in the car (MY) around the same time so
perhaps something happened then? LTE isn't working since (though wifi is
okay) and the car is in service now to fix that as well as a few other
things. I guess I'll wait until it gets back to check again. Is no one else
having the same issue after enabling 2FA?

**Comment by MikeBishop** [comment]
If you're comfortable poking at the API directly, could you see what `https://owner-api.teslamotors.com/api/1/vehicles/` is returning with your token in an `Authorization: Bearer (token here)` header?  I just want to be sure that Tesla is actually returning an empty list, rather than a bug that's causing it not to get interpreted properly.

**Comment by mwkrieger** [comment]
I'm getting a valid response. 
`{
    "response": [
        {
            "id": 58616505551737774,
            "vehicle_id": 1372781762,
            "vin": "****", (I took this out)
            "display_name": "Wattson",
            "option_codes": "AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0",
            "color": null,
            "access_type": "OWNER",
            "tokens": [
                "e38152336ab***", (I took some of these out)
                "d81ea412d938***"
            ],
            "state": "asleep",
            "in_service": true,
            "id_s": "58616505551737774",
            "calendar_enabled": true,
            "api_version": 10,
            "backseat_token": null,
            "backseat_token_updated_at": null,
            "vehicle_config": null
        }
    ],
    "count": 1
}`

**Comment by MikeBishop** [comment]
Hm.  Okay, next step would be to add `debug: true` to your config, and look at the debug console for the events it spews there, and the MM2 console output for the node_helper events there.  I'm guessing one of three things:

- In the event `TeslaAPIConfigured`, the vehicles member is empty; I don't see a reason for that to be the case if the API is returning the right thing, but that's how the API returning an empty list would manifest.
- There's some exception on the NodeHelper accessing the API and generating `VehicleData` events
- There's some exception in the handling of `VehicleData` events before they can populate the UI

Hopefully there's an error message that points us to the right next step.

**Comment by MikeBishop** [comment]
@mwkrieger, just checking back on this.

**Comment by mwkrieger** [comment]
Thanks for checking in. Everything is good. I think it was tied to a faulty
home link install that affected a lot of the systems in the car from
airbags to LTE.

**Comment by MikeBishop** [comment]
Glad to hear it!
