### ISSUE TITLE
Issue with solar production in PowerLine graph

### ISSUE THREAD

**Issue by Slavik714** [MikeBishop/MMM-Powerwall#18]
When one module with single graph PowerLine is enabled, there is no problem.
![image](https://user-images.githubusercontent.com/52895616/98761983-379f7700-239c-11eb-9131-dc2a0cf41084.png)

But, when I enable another MMM-Powerwall module with any other graph, I loose solar production in the first graph.
![image](https://user-images.githubusercontent.com/52895616/98761993-40904880-239c-11eb-92bf-1bfdfae99d9b.png)

```
modules: [
    	{
		module: 'MMM-Powerwall',
		position: 'top_left',
		config: {
			powerwallIP: '192.168.X.XXX',
			localUpdateInterval: '1000',
			graphs: ["PowerLine"],
			teslaAPIUsername: 'xxxxxxxxx@gmail.com',
			debug: true
		}
	},
    	{
		module: 'MMM-Powerwall',
		position: 'top_right',
		config: {
			powerwallIP: '192.168.X.XXX',
			localUpdateInterval: '1000',
			graphs: ["PowerwallSelfPowered"],
			teslaAPIUsername: 'xxxxxxxxx@gmail.com',
			debug: true
		}
    	},
```

**Comment by MikeBishop** [comment]
I think I found the issue.  The code which removed Car from the display if you don't have a TWCManager set up could run at the initialization of each graph, affected a global variable, and wasn't smart enough to only act once.  When it ran the second time, it took Solar out as well.

It's a little smarter now.  Pull and give it another shot?

**Comment by Slavik714** [comment]
Yep, it solved it. 
![image](https://user-images.githubusercontent.com/52895616/98828510-c690ab80-23fd-11eb-9e73-7cb9a35653b0.png)

Thanks.
