### ISSUE TITLE
Any chance on language support ?

### ISSUE THREAD

**Issue by McMornan** [MikeBishop/MMM-Powerwall#28]
Hi, 

great module, works like a charm. 

However I need to manually go through your source code to do a localization (e.g. for German). This is a little tedious. Any chance you'd consider supporting the language translation .json files ?

Thank you very much,
Lars

**Comment by MikeBishop** [comment]
Definitely something I've thought about.  Seems like it should be pretty straightforward.

The main complexity would probably be in the construction of the car status, which is built a word at a time; I could envision other languages requiring a different word ordering, which probably entails using placeholders to sub in the right words.  IIRC, German is such a language with different word ordering, so you might be in a good position to help figure that out.
