### ISSUE TITLE
Graphs Not Displaying

### ISSUE THREAD

**Issue by kestertonm** [MikeBishop/MMM-Powerwall#38]
I have followed the install instructions from the magic mirror site. Config is as follows.

          module: 'MMM-Powerwall',
            position: 'top_left',
            config: {
               powerwallIP: '192.168.0.8',
               teslaAPIUsername: "mike@kesterton.net",
               teslaAPIPassword: "XXXXXX",
               home: 'XX.48687,XXX.46614',
               graphs: "HouseConsumption"

The manual token file creation works! Thanks

There is no graph display on "House is consuming and amount" which is correct and nothing else.

What have I missed ? Thanks in advance!

**Comment by MikeBishop** [comment]
If the current usage and total for the day are both showing properly, it's collecting all the right information, so that's good.

If there's no graph, you might not have chart.js installed.  Did you do `npm install` after cloning the module repo?

**Comment by kestertonm** [comment]
Yes I made a NOOB error. It turns out that NEM install will run on the modules directory but doesn’t update the dependencies. I have now run it in the mmm-powerwall and all is good. Thank you very much.

**Comment by MikeBishop** [comment]
Happy to help!
