### ISSUE TITLE
Not operational after Tesla Powerwall update to 20.49

### ISSUE THREAD

**Issue by gbassaragh** [MikeBishop/MMM-Powerwall#44]
Suspect authentication error after powerwall updated to 20.49.

**Comment by MikeBishop** [comment]
I presume this was addressed by the recent changes in the module?

**Comment by gbassaragh** [comment]
I haven't been able to get it to work yet, but I saw the recent updates and figured I would try a few things first.

**Comment by MikeBishop** [comment]
Hm.  Does it stall when you authenticate to the API?  I'm seeing that now, but I don't understand why yet.  It doesn't seem to be related to the Powerwall change.

**Comment by gbassaragh** [comment]
Yes, that is the behavior I'm seeing.  I initially had MFA enabled and thought that may have been the culprit. I've removed MFA authentication from my Tesla account, doesn't seem to matter. 
Additionally I haven't had success whether I enter the password in the config.js or on the \MMM-Powerwall\auth page

**Comment by MikeBishop** [comment]
No, something strange is going on in code that didn't get changed from the Powerwall changes.  When it makes the call to supply the MFA token, it never gets a response back.  I'm not sure yet whether that's server-side behavior or something going on in the client.

**Comment by MikeBishop** [comment]
Well, I figured out the source of the stall, at least -- axios isn't seeing any response and has an infinite timeout by default.  I've added a timeout, so now it will at least tell you that the timeout was exceeded when making the call.  However, I'm not able to reproduce the timeout in Postman, so I'm uncertain *why* there's a timeout happening.

Given that this started happening without a change in previously-working code, I'm inclined to see if it gets resolved server-side in a few days.

**Comment by MikeBishop** [comment]
Yep -- this is a broader issue with Tesla's API.  https://github.com/timdorr/tesla-api/issues/321

**Comment by MikeBishop** [comment]
I've borrowed a (strange) workaround from TeslaMate that appears to get past the issue.  Give it another shot?

**Comment by gbassaragh** [comment]
Hi, yes I restarted MM and it seems to be working now. It did hangup about an hour later and had the "visit MMM-Powerwall/auth..." message. But restarting MM seems to have resolved that as well?

**Comment by MikeBishop** [comment]
Hm.  Was that for the API (showed username) or the Powerwall (showed IP address)?  It's possible there's a brief gap when the Cookie needs to be refreshed but hasn't been yet....
