### ISSUE TITLE
EnergyBar & PowerLine no data display

### ISSUE THREAD

**Issue by Eagle2301** [MikeBishop/MMM-Powerwall#47]
Hi,
First of all sorry for my English.
I am trying this awesome module and it seems to work very well with my Tesla Powerwall, but I have a problem with EnergyBar and PowerLine.
The other graphs work fine but nothing is shown in Powerline and EnergyBar.

I am probably missing something, can I ask for help?
Thank you 

![image](https://user-images.githubusercontent.com/26015862/111163912-d384fd80-859d-11eb-93da-d9ce87adfba3.png)

**Comment by MikeBishop** [comment]
Looks like none of the data from the Tesla API is populating; EnergyBar and PowerLine are purely driven by that data, while the others combine local and cloud data.  I don't see a prompt for you to sign in; is the Tesla username in the config file?

**Comment by MikeBishop** [comment]
(And if English is not your primary language, feel free to contribute a translation to whatever language is!  You'd just copy the `translations/en.json` file to your own language's code, then edit the strings with the text which should appear there.)

**Comment by Eagle2301** [comment]
Hi Mike,
Tanks for your quickly replay and for your explanation.
I have tray to insert the "TeslaAPIUsername" in the config file, and the system say me to go to "MMM-Powerwall/auth", but when insert a password (right user & right password of Tesla account) I receive this: 
![image](https://user-images.githubusercontent.com/26015862/111441525-b1a78a00-8707-11eb-8817-8c23bb4cbd17.png)

Thank you in advance for your help.

P.S. I will try to translate the file into Italian

**Comment by Eagle2301** [comment]
How do I send you the `translations/it.json` file?

**Comment by MikeBishop** [comment]
That seems to be a timeout issue that I've seen across multiple HTTP clients within Node when attempting to reach the Tesla auth server.  I have two machines it happens on, and two it doesn't, and I haven't yet figured out the difference between them.

**Comment by MikeBishop** [comment]
I'm very sorry for the delay -- I eventually gave up trying to solve the problem and worked around it instead.  Can you try the `python` branch (PR #49) and see if that fixes things for you?

BTW, the `translations/it.json` file would just go in a separate pull request.

**Comment by Eagle2301** [comment]
Thank you Mike, now work for me.

**Comment by MikeBishop** [comment]
Delighted to hear it!  I apologize again for letting it go so long.  I still don't understand why some Node installs can't talk to that API, but Python doesn't seem to have that problem.

If you browse to the `translations/` folder on GitHub and try to upload your file, it should offer to create a fork for you since you don't have write access.  Once you have a fork with a change in it, it should prompt you to create a PR to add the file back to this repo.

**Comment by Eagle2301** [comment]
Hi Mike,

I have created a pull request with the it.json file....  I hope it's right.
Thank you
