### ISSUE TITLE
MMM-Powerwall/auth gives scraping oauth form failed warning

### ISSUE THREAD

**Issue by rupertwilson** [MikeBishop/MMM-Powerwall#48]
Within the last few days attempting to enter Tesla login credentials via MMM-Powerwall/auth gives an error 

"scraping oauth form failed" 

this is for the Tesla API.  Logging into the local Powerwall API still works OK.

Any ideas?

**Comment by mwkrieger** [comment]
I'm seeing the same thing. Only part of the data is showing up now.

**Comment by MikeBishop** [comment]
Yes, this cropped up a while ago -- the request to Tesla's auth server times out.  It only seems to happen in Node and on Raspberry Pi; the same code works running on my desktop.  I haven't found a solution yet.

**Comment by MikeBishop** [comment]
I'm very sorry for the delay -- I eventually gave up trying to solve the problem and worked around it instead.  Can you try the `python` branch (PR #49) and see if that fixes things for you?

**Comment by rupertwilson** [comment]
Thanks for the workaround - I ran the python script with the required credentials and it seemed to update the tokens.json file  I then restarted the MagicMirror but the go to "MMM-Powerwall/auth to login message still shows"

**Comment by MikeBishop** [comment]
The script is used by the helper; you still sign in via the /auth page.
