### ISSUE TITLE
Auth issues with special characters in password

### ISSUE THREAD

**Issue by mwkrieger** [MikeBishop/MMM-Powerwall#53]
Hi again, Mike. I'm having a hard time with the module for some reason. Everything was working great with the module for the longest of times, then the other day I got the signin message on the screen. When I go to the /auth screen, I put in my username, password, and mfa into the system and I get an authentication failed error. The tokens.json file is blank, so I updated that with a backup that I had and when I restart things, that json file gets blanked out again. I have made sure that I've done a git pull, so I have the most current version - but it seems that there is absolutely nothing I can do to get things working again. 

The local data seems to work fine - no charts or anything, but at least some data is showing. I've tried to set debug: true in the config file, but I don't see any additional debug info being shown. I've verified that I'm using the correct credentials for Tesla as well.

Any insight?

**Comment by MikeBishop** [comment]
If it's blanking out the tokens.json file, I would guess the token from your backup is expired.  The current behavior is to discard the token if refresh fails and the token is past its expiration date, so you can sign in from a clean state.  What happens when you run:

    python3 tesla.py <username> <password> [<mfaToken>]

**Comment by MikeBishop** [comment]
And basic question -- have you done an `npm install` since getting the latest version?  Is `python3` accessible in your path?

**Comment by mwkrieger** [comment]
Got it to work manually. I have a ! in my password, so the tesla.py was throwing an error when I ran it. I changed my password to something without the bang and it worked. Copied the key in and it worked perfectly. 

One thing I do notice, and not sure how you'd be able to get around this is that when the gateway switches to a cellular connection, the screen goes blank. I assume it's because Tesla disables the wifi connection when the cellular connection is active. Not sure if there is a way to fall back or not. 

Anyway, thanks again!

**Comment by MikeBishop** [comment]
Hm, my password has characters that need to escape.  I think I've gotten around that by putting single quotes around the password, and passing it as a single value in an array *should* have the same effect.  I might need to put a `!` in my password and do some testing.  I'll leave this issue open to track.

**Comment by daterrell** [comment]
Adding a "me too" to this issue.  Using the auth page it definitely doesn't like bangs in passwords.  I changed to a password without a bang and it worked fine.

**Comment by MikeBishop** [comment]
Having poked at this for a while this evening, I can't find a way to escape the arguments properly so that this doesn't happen.  (Apparently the `!` is being interpreted through command history, so `passwor!d` becomes `passwordu -sh` or fails if you don't happen to have a command collision with the rest of your password.)

The better solution to this is probably to pass argments in environment variables instead of command-line arguments, but I'll come back to that another evening.

**Comment by daterrell** [comment]
Why not URL Encode, Base64, or something, then decode on the python side?  Agree, other ideas of sending passwords to a child process would be better, though -- other than special characters -- how much 'security' is involved is kind of minimal considering the environment.
