### ISSUE TITLE
Charts not displaying

### ISSUE THREAD

**Issue by johnfieldMM** [MikeBishop/MMM-Powerwall#55]
Recently had to reimplement (great job with the auth to support 2FA BTW!) but I am not getting the charts displaying for PowerwallSelfPowered, SolarProduction, HouseConsumption, EnergyBar and PowerLine. The data is there (when relevant) just not drawing a chart

**Comment by MikeBishop** [comment]
Have you done an `npm install` to make sure you have chartjs installed?  If there are no charts, that library being missing seems like the first culprit.

**Comment by johnfieldMM** [comment]
Aha I had done it but missed the WARN
npm WARN chartjs-plugin-datalabels@0.7.0 requires a peer of chart.js@>= 2.7.0 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN mmm-powerwall@1.0.0 No repository field.

**Comment by johnfieldMM** [comment]
Installed v2.9.0 of chart.js successfully

**Comment by MikeBishop** [comment]
Ah, I see!  `package.json` specifies `"chart.js": "latest",` but I'm not updated to support chartjs 3 yet.  (#32 tracking that.)  Which means `latest` now fails to install a compatible version.  I'll fix that ASAP.
