### ISSUE TITLE
Tesla API login fails with long (generated) password

### ISSUE THREAD

**Issue by daterrell** [MikeBishop/MMM-Powerwall#60]
Trying to authenticate both to Powerwall and Tesla API using the auth page.  I use a password manager and have a very long (100 char) password for Tesla.  `auth.njk` is truncating the password field to 30 characters.  

Easy enough to solve.

```
diff --git a/auth.njk b/auth.njk
index 8719d54..13775b7 100644
--- a/auth.njk
+++ b/auth.njk
@@ -27,7 +27,7 @@
     <input class="input" id="{{field}}" name="{{field}}" type="
       {{- "password" if field == "password" else "text" -}}
       " maxlength="
-      {{- 6 if field == "mfa" else 30 -}}
+      {{- 6 if field == "mfa" -}}
       " value="{{ data[field] }}">
     {% endif %}
```

---

(A note about #53 : I also have a bang ("!") in my password.  It appears to pass through to the node_helper fine; no idea how it looks being used as an arg spawning python.  I am also not able to authenticate.  I will comment on that issue).

**Comment by MikeBishop** [comment]
Thanks for poking at it!  30 seemed like a safe enough max, but apparently not.  :-)
