### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by daterrell** [MikeBishop/MMM-Powerwall#61]
Using `/MMM-Powerwall/auth` trying to authenticate to Powerwall gateway I get the titled error message.  I can login to the gateway fine with a browser.

**Comment by daterrell** [comment]
I got this working by upgrading Node.  I went on a guess and checked the TLS version in the browser (1.3), my node version (10) supposedly only up to TLS1.2.  I hope this isn't misinformation for anyone, but upgrading node (via `n latest` -> 16.5) it started working.

**Comment by MikeBishop** [comment]
Thanks for figuring it out!  Entirely possible they require TLS 1.3 on the Powerwall, since I also upgraded to Node latest in an attempt to troubleshoot TLS failures during auth to the Tesla API.
