### ISSUE TITLE
I'm cursed. Auth issues again

### ISSUE THREAD

**Issue by mwkrieger** [MikeBishop/MMM-Powerwall#69]
Mike - I've been having a problem that I can't seem to get to the bottom of. I can't use the webauth page when my token expires for some reason, so I've been using the tesla.py script that you mentioned in a previous post. This has stopped working now. I've turned off 2FA (I hate that...) and I've removed the ! in my password. When I pass my email/password to tesla.py, I'm getting the following: 

Post auth form success - 1 attempt(s).
Traceback (most recent call last):
  File "tesla.py", line 247, in <module>
    login(args)
  File "tesla.py", line 195, in login
    code = parse_qs(resp.headers["location"])[
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

I take a look at the response, and in fact, the response doesn't have a 'location' key in it. 

Any thoughts on how I can get this running again?

**Comment by Slavik714** [comment]
You're not alone. Looks like 'location' variable is not being passed back from Tesla side. Started today for me too.

**Comment by mwkrieger** [comment]
I'm glad I'm not going crazy. Any workaround I can try?

**Comment by MikeBishop** [comment]
Looks like they've added a Captcha step.  🤦‍♂️  It was there before, but I think turned off for certain UserAgent strings.  Apparently we no longer get a pass.  I'll have to figure out how to serve the Captcha.

I'm probably not going to have much time to focus on this until the weekend; sorry.

**Comment by MikeBishop** [comment]
There's also the question of why the refresh isn't working for you....  You should still be able to take a valid refresh token and get a new token.

**Comment by mwkrieger** [comment]
Got it, thanks. I can't get a refresh because my tokens.json is empty. Is there a format I can follow to recreate the Jason file manually? I know it has my email address in it - but I never thought to save one as a backup.

**Comment by MikeBishop** [comment]
```
{
    "yourmail@example.com": {
        "access_token": "foo",
        "token_type": "bearer",
        "expires_in": 3888000,
        "refresh_token": "bar",
        "created_at": 1629489475
    }
}
```

**Comment by mwkrieger** [comment]
That did the trick. Thank you!
