### ISSUE TITLE
Email address showing to left of chart

### ISSUE THREAD

**Issue by Stoobiedoo** [MikeBishop/MMM-Powerwall#84]
I want to use a single chart in the lower left corner of my MM. I selected the PowerwallSelfPowered. It shows, but there is also my email address to the left, which pushes the meter towards the middle.
Is there some setting to remove the email address? Thanks

![MM_PowerWallIssue](https://user-images.githubusercontent.com/6288850/156704361-54af9269-7fad-4d98-af3b-0bb158140211.png)

**Comment by Stoobiedoo** [comment]
Configuration file setup.
![MM_PowerWallIssue_config](https://user-images.githubusercontent.com/6288850/156704801-988bd6b7-1f36-4544-8d12-a026a4710a71.png)

**Comment by MikeBishop** [comment]
As it says [here](https://github.com/MikeBishop/MMM-Powerwall#authentication), you need to go to the indicated page and provide Tesla API tokens.  That tile gets inserted if it's configured to use an information source (either the API or the local Powerwall) and it doesn't have authentication for that source.

**Comment by Stoobiedoo** [comment]
Thanks for looking into it. Seems the issue was still having log in info in
the config file after running the authentication steps. Removing my login
email and password resolved the issue.
