### ISSUE TITLE
Token Not Valid

### ISSUE THREAD

**Issue by macaday** [MikeBishop/MMM-Powerwall#87]
I cannot seem to log in using my access and refresh tokens.  I'm using the Authla app as recommended but every time I get a "Token Not Valid" error.  I've tried revoking/refreshing the tokens but still nothing.  What am I missing here?

<img width="461" alt="image" src="https://user-images.githubusercontent.com/43648452/181619263-4f9265a0-7408-4d87-8baf-f4f83cdba830.png">

**Comment by MikeBishop** [comment]
Token refresh (which also happens when a token is first submitted) depends on Python.  Confirm that `python3` exists in the path.  Assuming it does, try running `python3 ./refresh.py <your_refresh_token>` and see if it succeeds.

**Comment by macaday** [comment]
That did the trick!  I apologize I missed the line in the readme talking about making sure python3 and the requests module were installed.  I'm still having trouble with some of the graphs but I'll fiddle around a bit more on my own before I bug you again.  Thanks so much!
